Logger Class Reference
Basic Logger.
#include <Logger.h>
Public Member Functions
void setLogLevel (LogLevel level)
void setLogOutput (std::ostream *output)
void log (LogLevel level, const std::string &message)
void debug (const std::string &message)
void info (const std::string &message)
void warning (const std::string &message)
void error (const std::string &message)
void critical (const std::string &message)
Static Public Member Functions
static Logger & getInstance ()
Detailed Description
Definition at line 25 of file Logger.h.
Member Function Documentation
critical()
void critical (const std::string & message) [inline]
Definition at line 56 of file Logger.h.
debug()
void debug (const std::string & message) [inline]
Definition at line 52 of file Logger.h.
error()
void error (const std::string & message) [inline]
Definition at line 55 of file Logger.h.
Referenced by FurrBall::CreateBall(), and MemoryManager::ProtectMemory().
getInstance()
static Logger & getInstance () [inline], [static]
Definition at line 33 of file Logger.h.
Referenced by FurrBall::CreateBall(), and MemoryManager::ProtectMemory().
info()
void info (const std::string & message) [inline]
Definition at line 53 of file Logger.h.
log()
void log (LogLevel level, const std::string & message) [inline]
Definition at line 45 of file Logger.h.
Referenced by Logger::critical(), Logger::debug(), Logger::error(), Logger::info(), and Logger::warning().
setLogLevel()
void setLogLevel (LogLevel level) [inline]
Definition at line 37 of file Logger.h.
setLogOutput()
void setLogOutput (std::ostream * output) [inline]
Definition at line 41 of file Logger.h.
warning()
void warning (const std::string & message) [inline]
Definition at line 54 of file Logger.h.
Referenced by FurrBall::CreateBall().
The documentation for this class was generated from the following file:
Furrballs/include/Logger.h