project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - whitepaper.qmd
    - remarc-paper.qmd
  resources:
    - CNAME

website:
  title: "Furrballs"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: whitepaper.qmd
        text: Whitepaper
      - href: remarc-paper.qmd
        text: REMARC Paper

format:
  html:
    toc: true
    number-sections: true
    code-fold: false

execute:
  enabled: false
